spring.application.name=demo

# DATABASE
spring.datasource.url=jdbc:postgresql://localhost:5432/expense_tracker
spring.datasource.username=postgres
spring.datasource.password=1234

# JDBC
spring.datasource.driver-class-name=org.postgresql.Driver

# FLYWAY
spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration

# SERVER
server.port=8080